export default {
  user: {
    home: "/",
    login: "/login",
    register: "register",
    resetpassword: "resetpassword",
    about: "about",
    contact: "contact",
    HeaderNav: "navbar",
    askFatwas: "/ask-fatwas",
    fatwas: "/fatwas",
    accountUser: "/user",
    accountUserHome: "/user/home",
    accountUserProfile: "/user/profile",
    accountUserAsk: "/user/ask",
    fatwasDetailsPage: "/fatwa-details",
  },
  admin: {
    admin: "/admin",
    login: "login",
    adminfatwas: "fatwas",
    musthafthies: "musthafthies",
    user: "user",
    category: "category",
    article: "article",
    addArticle: "addArticle",
    addCategories: "addCategories",
    addMufthi: "addMufthi",
    addUser: "addUser",
    fatwasDetails: `fatwa-details`,
    dashboard: "dashboard",
  },
};
