import { Container, Divider, Grid, Paper, Typography } from "@mui/material";
import "./privacypolicy.styles.scss";
export default function PrivacyAndPolicy() {
  return (
    <Container className="privacy-policy-section">
      <Grid spacing={3}>
        <Grid item md={12}>
          <Typography
            variant="h5"
            align="center"
            className="text-decoration-underline"
          >
            Privacy Policy Darul Ifta Kauzariyya
          </Typography>
        </Grid>
        <Grid item md={12} marginTop={1}>
          <Typography variant="subtitle2" align="center" className="fw-bold">
            Updated at 2022-01-01
          </Typography>
        </Grid>
        <Grid item md={12} marginTop={5} marginBottom={3}>
          <Typography
            variant="paragraph"
            sx={{ lineHeight: 1.8, textAlign: "justify" }}
          >
            <b> DARUL IFTA KAUZARIYYA.</b> ("we," "our," or "us") is committed
            to protecting your privacy. This Privacy Policy explains how your
            personal information is collected, used, and disclosed by DARUL IFTA
            KAUZARIYYA. This Privacy Policy applies to our <b>website :-</b>
            <a href="">daruliftakauzariyya.com </a>, and its associated
            subdomains (collectively, our "Service") alongside our application,
            DARUL IFTA KAUZARIYYA. By accessing or using our Service, you
            signify that you have read, understood, and agree to our collection,
            storage, use, and disclosure of your personal information as
            described in this Privacy Policy and our Terms of Service.
          </Typography>
        </Grid>
        <Divider />
      </Grid>
      <Grid item md={12} marginTop={4}>
        <Paper elevation={2} className="p-4">
          <Grid item md={12} marginTop={4}>
            <Typography variant="h5">Definitions and key terms</Typography>
          </Grid>
          <Grid item md={12} marginTop={1}>
            <Typography variant="paragraph">For this Privacy Policy</Typography>
          </Grid>
          <Grid item md={12} marginTop={4} marginBottom={4} className="listing-section">
            <ul>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                  Cookie: small amount of data generated by a website and saved
                  by your web browser. It is used to identify your browser,
                  provide analytics, remember information about you such as your
                  language preference or login information.
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                  Company: when this policy mentions "Company," "we," "us," or
                  "our," it refers to Kauzariyya, Al Jamiathul Kauzariyya,
                  Edathala north po, Aluva, Ernakulam, Kerala, India pin 683561
                  that is responsible for your information under this Privacy
                  Policy.
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                Country: where DARUL IFTA KAUZARIYYA or the owners/founders of DARUL IFTA KAUZARIYYA are based in this case is Kauzariyya.
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                Customer: refers to the company, organization or person that signs up to use the DARUL IFTA KAUZARIYYA Service to manage the relationships with your consumers or service users.
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit DARUL IFTA KAUZARIYYA and use the services.
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet Personnel: refers to those individuals who are employed by DARUL IFTA KAUZARIYYA or are under contract to perform a service on behalf of one of the parties
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                Personal Data: any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                Service: refers to the service provided by DARUL IFTA KAUZARIYYA as described in the relative terms (if available) and on this platform.
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                Website: DARUL IFTA KAUZARIYYA's site, which can be accessed via this URL: www.daruliftakauzariyya.com
                </Typography>
              </li>
              <li>
                <Typography variant="paragraph" sx={{ lineHeight: 1.8, textAlign: "justify" }}>
                You: a person or entity that is registered with DARUL IFTA KAUZARIYYA to use the Services.
                </Typography>
              </li>
            </ul>
          </Grid>
        </Paper>
      </Grid>
    </Container>
  );
}
